# Generated by Django 4.2 on 2023-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
    ]
